### ISSUE TITLE
How to only check OTP middleware if user logged in?

### ISSUE THREAD

**Issue by frequentredundancy** [makelarisjr/laravel-2fa#15]
This package works great but i want to know if it's possible for me to configure the middleware in a way where on every route it checks the OTP if the user is logged in only. Because I have some routes that are public, but if a user is logged in I also want to check OTP if they try access these routes.

With the current middleware, if you try do this, it complains on the public pages if you aren't logged in.

**Comment by meletisf** [comment]
Hello,

Apologies for the late response. 

You can always override the default middleware: https://github.com/makelarisjr/laravel-2fa/blob/master/src/Http/Middleware/OTPMiddleware.php

Apart from that, there is no other check the occurs.
